filebeat.inputs:
- type: log
  paths:
    - /var/log/system.log
    - /var/log/wifi.log

filebeat.modules:
  #Filebeat system module consumes logs from host OS through a mounted volume.
  - module: system
    syslog:
      var.paths: ["/var/log/host/system.log*"]

  - module: traefik
    access:
      enabled: true
      var.paths: ["/var/log/traefik/*"]

xpack.monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
